package com.zcbspay.platform.support.task.bean;
// Generated 2015-11-9 9:45:58 by Hibernate Tools 4.0.0


/**
 * TTxnsNotifyTask generated by hbm2java
 */

public class NotifyTaskBean implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1112312515568183790L;
    private long id;
    private String memberId;
    private String txnseqno;
    private Integer sendTimes;
    private Integer maxSendTimes;
    private String data;
    private String sendStatus;
    private String httpRescode;
    private String notifyUrl;
    private String taskType;
    public NotifyTaskBean() {
    }

    public NotifyTaskBean(long id) {
        this.id = id;
    }
    public NotifyTaskBean(long id, String memberId, String txnseqno,
            Integer sendTimes, Integer maxSendTimes, String data,
            String sendStatus, String httpRescode, String notifyUrl) {
        this.id = id;
        this.memberId = memberId;
        this.txnseqno = txnseqno;
        this.sendTimes = sendTimes;
        this.maxSendTimes = maxSendTimes;
        this.data = data;
        this.sendStatus = sendStatus;
        this.httpRescode = httpRescode;
        this.notifyUrl = notifyUrl;
    }
    public NotifyTaskBean(String memberId, String txnseqno,
            int sendTimes, int maxSendTimes, String data,
            String sendStatus, String httpRescode, String notifyUrl,String taskType) {
        this.id =1L;
        this.memberId = memberId;
        this.txnseqno = txnseqno;
        this.sendTimes = sendTimes;
        this.maxSendTimes = maxSendTimes;
        this.data = data;
        this.sendStatus = sendStatus;
        this.httpRescode = httpRescode;
        this.notifyUrl = notifyUrl;
        this.taskType = taskType;
    }

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getMemberId() {
		return memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getTxnseqno() {
		return txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	public Integer getSendTimes() {
		return sendTimes;
	}

	public void setSendTimes(Integer sendTimes) {
		this.sendTimes = sendTimes;
	}

	public Integer getMaxSendTimes() {
		return maxSendTimes;
	}

	public void setMaxSendTimes(Integer maxSendTimes) {
		this.maxSendTimes = maxSendTimes;
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getSendStatus() {
		return sendStatus;
	}

	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}

	public String getHttpRescode() {
		return httpRescode;
	}

	public void setHttpRescode(String httpRescode) {
		this.httpRescode = httpRescode;
	}

	public String getNotifyUrl() {
		return notifyUrl;
	}

	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}

	public String getTaskType() {
		return taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}
    

}
